name Uptime Monitor
on: 
  schedule:
  #Run every minute
  -cron: '*****'

jobs:
    ping_site:
      runs-on: ubuntu-latest
      name: Uptime Check
      steps:
      - name: Uptime Action
        uses: srt32/uptime@v0.2.1
        with:
          url-to-hit: "https://super-giggle-9vrrwgqvjw7h77jw.github.dev/"
          expected-statusses: "200"
